const recipes = [
    {
        CookTime: 11.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4551476.jpg",
        Ingredients: [
            "2 (7 ounce) containers Greek yogurt",
            "1 cucumber, peeled and diced",
            "2 tablespoons chopped fresh mint",
            "2 tablespoons chopped fresh cilantro",
            "\u00bd teaspoon ground cumin",
            "salt and ground black pepper to taste",
        ],
        Instructions: "Combine Greek yogurt, cucumber, mint, cilantro, cumin, salt, and pepper in a bowl; mix well.",
        Name: "Easy Raita with Mint and Cilantro",
        PrepTime: 4.0,
        Review: 2.0,
        ReviewNum: 85.0,
        TotalTime: 15.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "8 servings",
    },
    {
        CookTime: 11.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F32810.jpg",
        Ingredients: [
            "1 bunch fresh cilantro",
            "1 clove garlic",
            "1 tablespoon minced fresh ginger root",
            "1 minced hot green chile peppers",
            "1 tablespoon peanuts",
            "salt to taste",
            "2 tablespoons lemon juice",
        ],
        Instructions:
            "Blend the following in a food processor until smooth: cilantro, garlic, ginger, green chili, peanuts, salt to taste, and lemon juice. Add a few drops of water if the mixture is too dry.",
        Name: "Green Chutney",
        PrepTime: 4.0,
        Review: 2.0,
        ReviewNum: 52.0,
        TotalTime: 15.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "4 servings",
    },
    {
        CookTime: 32.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F376248.jpg",
        Ingredients: [
            "1 tablespoon vegetable oil",
            "\u00bd cup chopped onion",
            "3 (19 ounce) cans garbanzo beans, drained",
            "2 tablespoons curry paste",
            "\u00bd cup apple juice",
            "3 sheets frozen puff pastry, thawed",
            "\u00bc cup all-purpose flour for dusting",
        ],
        Instructions:
            "Preheat oven to 350 degrees F (175 degrees C).\nHeat oil in a large skillet over medium-high heat. Saute onion until browned, about 5 minutes. Reduce heat and add garbanzo beans. Mix curry paste with apple juice until smooth, then add to skillet. Simmer mixture 10 minutes, stirring occasionally and adding more apple juice or water as needed to keep mixture moist.\nCut each sheet of pastry into 3 equal-size rectangles, then cut each rectangle in half. (You will have 18 pieces total.) Dust a clean, flat surface lightly with flour, and roll each piece of pastry until it is double in size. Dust pastry with flour as needed, to prevent it from sticking to rolling pin. Spoon an equal amount of filling into center of each pastry square. Fold in half and press edges to seal. Place on nonstick baking sheets.\nBake in preheated oven for 25 minutes, until golden brown.",
        Name: "Easy Veggie Samosas",
        PrepTime: 13.0,
        Review: 3.5,
        ReviewNum: 84.0,
        TotalTime: 45.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "18 samosas",
    },
    {
        CookTime: 28.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F251822.jpg",
        Ingredients: [
            "2 cups split pea flour",
            "1 cup self-rising flour",
            "\u00bc teaspoon baking powder",
            "\u00bd teaspoon turmeric",
            "\u00bd teaspoon cumin",
            "1 teaspoon salt",
            "\u00be cup water, or as needed",
            "\u00bd small onion, minced",
            "2 \u00bd cloves garlic, minced",
            "1 green onion, chopped (green part only)",
            "2 cups vegetable oil for frying",
        ],
        Instructions:
            "Sift the split pea flour, self-rising flour, and baking powder into a large bowl. Stir in turmeric, cumin, and salt. Gradually stir in enough water to make a very thick batter. Stir in onion, garlic, and green onion.\nHeat oil in a large heavy skillet over medium-high heat. When the oil is very hot, drop tablespoonfuls of the batter into the pan, and fry until golden brown on both sides. Remove to paper towels to drain.",
        Name: "Elijah's Phulourie",
        PrepTime: 12.0,
        Review: 2.5,
        ReviewNum: 84.0,
        TotalTime: 40.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "3 dozen",
    },
    {
        CookTime: 420.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1039317.jpg",
        Ingredients: [
            "4 pounds sliced peeled peaches",
            "1 cup raisins",
            "2 cloves garlic, minced",
            "\u00bd cup chopped onion",
            "5 ounces chopped preserved ginger",
            "1 \u00bd tablespoons chili powder",
            "1 tablespoon mustard seed",
            "1 teaspoon curry powder",
            "4 cups packed brown sugar",
            "4 cups apple cider vinegar",
            "\u00bc cup pickling spice",
        ],
        Instructions:
            "In a large heavy pot, stir together the peaches, raisins, garlic, onion, preserved ginger, chili powder, mustard seed, curry powder, brown sugar and cider vinegar. Wrap the pickling spice in a cheesecloth bag, and place in the pot.\nBring to a boil, and cook over medium heat uncovered until the mixture reaches your desired consistency. It will take about 1 1/2 hours to get a good thick sauce. Stir frequently to prevent scorching on the bottom.\nRemove the spice bag, and ladle into hot sterilized jars. Wipe the rims with a clean moist cloth. Seal with lids and rings, and process in a barely simmering water bath for 10 minutes, or the time recommended by your local extension for your area. The water should cover the jars completely.",
        Name: "Spicy Peach Chutney",
        PrepTime: 180.0,
        Review: 3.0,
        ReviewNum: 83.0,
        TotalTime: 600.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "6 - 1/2 pints",
    },
    {
        CookTime: 25.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F768310.jpg",
        Ingredients: [
            "1 cup red lentils",
            "1 onion, chopped",
            "2 \u00bd cups water",
            "2 teaspoons curry powder",
            "\u00be teaspoon cayenne pepper",
            "1 tablespoon vegetable oil",
            "2 cloves crushed garlic",
            "1 teaspoon cumin seeds",
        ],
        Instructions:
            "In a medium saucepan combine the lentils, onion and water. Cover and bring to a boil. Reduce heat to low and simmer for 25 minutes or until lentils are soft. Pass lentils through a food mill or blend them in a blender.\nToast curry powder and cumin seeds in a small skillet over medium heat until fragrant. Add cayenne, oil and garlic. Saute for 1 minute.\nStir spice mixture into lentils and serve.",
        Name: "Spicy Lentil Dip",
        PrepTime: 10.0,
        Review: 3.5,
        ReviewNum: 70.0,
        TotalTime: 35.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "2 cups",
    },
    {
        CookTime: 20.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1133714.jpg",
        Ingredients: [
            "\u00bd cup garbanzo beans",
            "2 cups plain yogurt",
            "1 teaspoon grated fresh ginger",
            "\u00bd teaspoon chili powder",
            "\u00bc teaspoon ground cumin",
            "\u00bc teaspoon ground coriander seed",
            "\u00bc teaspoon rock salt",
            "\u00bc teaspoon ground black pepper",
            "salt to taste",
            "1 large potato - peeled, boiled and mashed",
            "32 thin wheat crackers",
            "\u00bc cup green chutney",
            "\u00bc cup sweet and sour chutney",
            "\u00bd cup red onion, minced",
            "\u00bd cup chopped fresh cilantro",
            "\u00bd cup crushed potato chips",
        ],
        Instructions:
            "Boil the garbanzo beans in water for about 30 minutes or until tender when pierced with a fork; drain well.\nBeat the yogurt together with the following: fresh grated ginger, chili powder, cumin powder, coriander powder, rock salt or black salt, black pepper and salt.\nSeason the mashed potato with salt.\nBreak each puri gently with a fork to create a tiny opening on the top. Arrange the puris in 4 plates, 8 in each plate. Or, if using wheat crackers arrange them on a platter or plates. Place the potatoes on top of each cracker. Place about 1 tablespoon of potato in each puri or on each cracker. Place a few garbanzo beans on top of the potato. Spoon the spiced yogurt on top. Spoon green chutney and sweet and sour chutney on top of it. Garnish with the chopped onion, cilantro, and sev on top. Serving tip: I like to set up a number of small bowls with each of the above condiments, so that each person can add whatever they want to, according to their taste and preferences.",
        Name: "Chaat - Dahi Batata Puri",
        PrepTime: 10.0,
        Review: 3.0,
        ReviewNum: 76.0,
        TotalTime: 30.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "4 servings",
    },
    {
        CookTime: 4.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4560037.jpg",
        Ingredients: [
            "1 onion, chopped",
            "2 teaspoons ketchup",
            "1 teaspoon lemon juice",
            "1 tablespoon white sugar",
            "1 pinch salt",
            "1 teaspoon chopped fresh cilantro",
            "1 teaspoon chopped fresh fenugreek leaves",
            "1 teaspoon chili powder",
        ],
        Instructions:
            "In a medium bowl, stir onion and ketchup until onion is thinly and evenly coated. Mix in the lemon juice. Season with sugar, cilantro, fenugreek and chili powder, and mix thoroughly. Cover, and chill for 24 hours. This allows the lemon juice to neutralize the onion flavor slightly.",
        Name: "Indian Spiced Onions",
        PrepTime: 1.0,
        Review: 3.5,
        ReviewNum: 90.0,
        TotalTime: 5.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "4 servings",
    },
    {
        CookTime: 109.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F287314.jpg",
        Ingredients: [
            "2 cups canned chickpeas, rinsed and drained",
            "1 tablespoon lemon juice",
            "2 tablespoons olive oil",
            "1 teaspoon brown sugar",
            "1 \u00bd teaspoons ground cumin",
            "\u00bd teaspoon ground coriander",
            "\u00bc teaspoon ground cinnamon",
            "1 teaspoon garam masala",
            "1 pinch ground black pepper",
            "1 pinch cayenne pepper, or to taste",
            "\u00bd teaspoon salt, or to taste",
        ],
        Instructions:
            "Preheat oven to 400 degrees F (200 degrees C). Line a baking sheet with aluminum foil.\nStir together the chickpeas, lemon juice, olive oil, brown sugar, cumin, coriander, cinnamon, garam masala, black pepper, cayenne pepper, and salt in a mixing bowl. Spread the chickpea mixture in a single layer on the prepared baking sheet.\nRoast in the preheated oven until the chickpeas are dark brown in spots, crisp, and have shrunk quite a bit, 25 to 30 minutes, stirring halfway through the cooking time. Cool to room temperature before serving.",
        Name: "Indian-Spiced Roasted Chickpeas",
        PrepTime: 46.0,
        Review: 3.5,
        ReviewNum: 95.0,
        TotalTime: 155.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "1 1/2 cups",
    },
    {
        CookTime: 32.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F997136.jpg",
        Ingredients: [
            "5 medium-size potatoes, washed thoroughly",
            "2 teaspoons salt",
            "2 tablespoons garam masala",
            "2 tablespoons coriander powder",
            "2 tablespoons black pepper",
            "10 cilantro leaves, chopped",
            "6 tablespoons bread crumbs",
            "oil for frying",
        ],
        Instructions:
            "Place unpeeled potatoes in a large saucepan, fill with water, and place over high heat. Bring to a boil; cook until potatoes are soft and tender. Drain, cool, and peel potatoes.\nPlace potatoes in a large bowl. Add salt, garam masala, coriander powder, pepper, and cilantro. Mash with a large fork or potato masher until there are no lumps. Shape potatoes into flat cutlets, about 2 or 3 inches in diameter and 1 inch thick. Coat each cutlet lightly in bread crumbs, and set aside.\nHeat about 2 tablespoons oil in a large skillet over medium heat. Fry potato cutlets in batches until golden brown on both sides. Between batches, add oil as needed.",
        Name: "Potato Cutlets",
        PrepTime: 13.0,
        Review: 3.0,
        ReviewNum: 68.0,
        TotalTime: 45.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "10 servings",
    },
    {
        CookTime: 21.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1164455.jpg",
        Ingredients: [
            "1 cup vegetable oil for frying, or as needed",
            "2 cloves garlic, pressed",
            "1 teaspoon cumin seeds",
            "\u00bd teaspoon salt",
            "\u00bc teaspoon ground turmeric",
            "\u00bc teaspoon ground black pepper",
            "5 russet potatoes, peeled and cubed",
            "2 tablespoons chopped fresh cilantro",
            "1 teaspoon mild curry paste (such as Patak's\u00ae)",
        ],
        Instructions:
            "Pour enough oil into a frying pan to cover the bottom 1/3-inch deep; add garlic, cumin, salt, turmeric, and black pepper. Heat oil mixture over medium heat.\nCook and stir potatoes in the hot oil, turning occasionally, until cooked through, golden brown, and crisp on the outside, 10 to 15 minutes. Add fresh cilantro and curry paste and stir to coat. Fry until cilantro is dark green and crisp, about 1 more minute. Remove potatoes with a slotted spoon and transfer to serving dish.",
        Name: "Indian Curry Potato Fries",
        PrepTime: 9.0,
        Review: 4.0,
        ReviewNum: 65.0,
        TotalTime: 30.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "5 servings",
    },
    {
        CookTime: 18.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5589799.jpg",
        Ingredients: [
            "1 tablespoon olive oil",
            "4 medium onions, sliced into 1/4-inch thick rings",
            "\u00bd teaspoon turmeric powder",
            "\u00bd teaspoon ground coriander",
            "\u00bc teaspoon ground cumin",
            "\u00bc teaspoon ground ginger",
            "\u00bc teaspoon chili powder",
            "3 tablespoons all-purpose flour",
            "2 tablespoons garam masala",
            "\u00bd teaspoon salt",
            "\u00bd teaspoon ground coriander",
            "\u00bd teaspoon granulated garlic",
            "\u00bd teaspoon turmeric powder",
            "\u00bc teaspoon ground cumin",
            "1 pinch saffron",
            "2 teaspoons tomato paste",
            "2 tablespoons water",
            "vegetable oil for frying",
        ],
        Instructions:
            "Heat olive oil in a skillet over medium heat and cook onions until soft and translucent without browning them, about 5 minutes.\nAdd turmeric, coriander, cumin, ginger, and chili powder and stir in evenly until onions take on a uniform color. Remove from heat.\nPut onions in a mixing bowl. Combine flour, garam masala, salt, coriander, garlic, turmeric, cumin, and saffron in a small bowl. Add spice mix to the onions and mix until well coated. Stir water and tomato paste together in a bowl and pour over onion mixture. Stir everything together. Batter should be easy to stir but not sloppy or sticky. Add more water, 1 teaspoon at a time, if batter is too sticky.\nHeat oil in a large saucepan to 350 degrees F (175 degrees C). Add a large spoonful of batter to the hot oil and deep fry for 30 to 45 seconds. Turn bhaji over and fry until golden brown and crispy, another 30 seconds. Remove and drain on paper towels. Repeat with remaining batter.",
        Name: "Onion Bhaji",
        PrepTime: 7.0,
        Review: 2.0,
        ReviewNum: 86.0,
        TotalTime: 25.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "4 servings",
    },
    {
        CookTime: 25.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6347584.jpg",
        Ingredients: [
            "1 (16 ounce) package frozen peas",
            "1 tablespoon vegetable oil",
            "1 teaspoon cumin seeds",
            "1 teaspoon ground cumin",
            "salt to taste",
            "\u00bd teaspoon dried mango powder (amchoor)",
            "1 tablespoon chopped fresh cilantro",
        ],
        Instructions:
            "Place peas in a bowl and cover with water; soak for 20 minutes. Drain.\nHeat oil in a frying pan over medium heat. Add cumin seeds and cook until they start to crackle, about 1 minute. Add peas, cumin powder, and salt. Reduce heat and cover pan. Cook, stirring occasionally, until peas are tender and hot throughout, about 10 minutes.\nRemove frying pan from heat. Stir in dried mango powder. Mix cilantro into peas and serve hot.",
        Name: "Quick and Savory Indian Peas",
        PrepTime: 10.0,
        Review: 3.5,
        ReviewNum: 81.0,
        TotalTime: 35.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "2 servings",
    },
    {
        CookTime: 375.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F8223581.jpg",
        Ingredients: [
            "\u00be cup dried brown lentils",
            "3 tablespoons olive oil, divided",
            "1 onion, diced",
            "2 teaspoons curry powder",
            "1 teaspoon ground cardamom",
            "1 teaspoon ground ginger",
            "1 teaspoon ground cumin",
            "1 pinch cayenne pepper",
            "1 yam, peeled and sliced",
            "\u00bd cup water",
            "\u00bc cup coconut milk",
            "6 dried apricots, chopped",
            "\u00bd teaspoon sea salt",
            "1 (16 ounce) package samosa pastry (egg roll wrappers)",
        ],
        Instructions:
            "Place lentils into a bowl and cover with several inches of cool water; let stand 8 hours to overnight. Drain and rinse.\nPreheat oven to 350 degrees F (175 degrees C).\nHeat 1 tablespoon olive oil in a wok or large skillet over medium heat; cook and stir onion until softened, 5 to 10 minutes. Add curry powder, cardamom, ginger, cumin, and cayenne pepper; stir to coat. Mix lentils, yam, water, and coconut milk into onion mixture; cook and stir over low heat until liquid is mostly reduced and lentils are tender, about 20 minutes. Remove wok from heat and lightly mash mixture.\nSpoon about 1 1/2 tablespoons lentil mixture into the center of each pastry; fold pastry over filling creating a triangle. Fold edges into the triangle to seal. Arrange samosas on a baking sheet and brush remaining olive oil over the top.\nBake in the preheated oven until golden brown, 15 to 20 minutes.",
        Name: "Lentil Samosas",
        PrepTime: 160.0,
        Review: 4.0,
        ReviewNum: 62.0,
        TotalTime: 535.0,
        Type: "appetizer",
        Veg: 1.0,
        Yields: "8 servings",
    },
    {
        CookTime: 186.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F6515113.jpg",
        Ingredients: [
            "2 teaspoons ground coriander",
            "2 teaspoons ground cumin",
            "\u00bd teaspoon ground cardamom",
            "\u00bd teaspoon hot chile powder",
            "\u00bd teaspoon ground black pepper",
            "\u00bc teaspoon ground cloves",
            "1 tablespoon vegetable oil",
            "1 tablespoon water",
            "1 teaspoon salt, or more as needed",
            "5 large chicken wings, cut in 2, tips discarded",
        ],
        Instructions:
            "Combine coriander, cumin, cardamom, chile powder, pepper, and cloves in a dry pan over low heat. Stir until fragrant. Remove from heat, add oil and water, and stir until combined. Set spice paste aside.\nRub salt over wings in a shallow dish, then rub spice paste all over. Cover and refrigerate, 4 hours to overnight.\nPreheat an outdoor grill for high heat and lightly oil the grate. Add wings and cook, turning halfway, until well browned, 15 to 20 minutes. An instant-read thermometer inserted near the bone should read 165 degrees F (74 degrees C).",
        Name: "Indian Masala Chicken Wings",
        PrepTime: 79.0,
        Review: 2.0,
        ReviewNum: 63.0,
        TotalTime: 265.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "10 chicken wings",
    },
    {
        CookTime: 28.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F609167.jpg",
        Ingredients: [
            "2 large potatoes, peeled",
            "1 cup frozen peas, thawed",
            "2 tablespoons vegetable oil",
            "\u00bd teaspoon cumin seeds",
            "1 bay leaf, crushed",
            "2 large onions, finely chopped",
            "1 pound ground beef",
            "4 cloves garlic, crushed",
            "1 tablespoon minced fresh ginger root",
            "\u00bd teaspoon ground black pepper",
            "1 \u00bd teaspoons salt",
            "1 teaspoon ground cumin",
            "1 teaspoon ground coriander",
            "1 teaspoon ground turmeric",
            "1 teaspoon chili powder",
            "\u00bd teaspoon ground cinnamon",
            "\u00bd teaspoon ground cardamom",
            "2 tablespoons chopped fresh cilantro",
            "2 tablespoons chopped green chile peppers",
            "1 quart oil for deep frying",
            "1 (16 ounce) package phyllo dough",
        ],
        Instructions:
            "Bring a medium saucepan of lightly salted water to a boil. Stir in potatoes and peas. Cook until potatoes are tender but still firm, about 15 minutes. Drain, mash together and set aside.\nIn a large saucepan over medium high heat, heat the oil. Brown cumin seeds and bay leaf. Mix in onions and ground beef. Cook until beef is evenly brown and onions are soft, about 5 minutes. Mix in garlic, fresh ginger root. Season with black pepper, salt, cumin, coriander, turmeric, chili powder, cinnamon and cardamom. Stir in the mashed potato mixture. Remove from heat and chill in the refrigerator for 1 hour, or until cool.\nHeat oil in a large, heavy saucepan over high heat.\nMix cilantro and green chile peppers into the potato and beef mixture. Place approximately 1 tablespoon of the mixture onto each phyllo sheet. Fold sheets into triangles, pressing edges together with moistened fingers.\nIn small batches, fry until golden brown, about 3 minutes. Drain on paper towels and serve warm.",
        Name: "Beef Samosas",
        PrepTime: 12.0,
        Review: 3.0,
        ReviewNum: 76.0,
        TotalTime: 40.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "18 samosas",
    },
    {
        CookTime: 35.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2681532.jpg",
        Ingredients: [
            "2 cups all-purpose flour",
            "\u00bd teaspoon salt",
            "2 tablespoons butter",
            "\u00bc cup water",
            "1 quart oil for deep frying",
            "2 tablespoons butter",
            "1 small onion, chopped",
            "2 cloves garlic, chopped",
            "2 green chile peppers, chopped",
            "1 tablespoon fresh ginger root, chopped",
            "\u00bd teaspoon ground turmeric",
            "\u00bd teaspoon chili powder",
            "\u00be pound ground lamb",
            "1 teaspoon salt",
            "2 teaspoons garam masala",
            "1 \u00bd tablespoons fresh lemon juice",
        ],
        Instructions:
            "In a medium bowl, mix flour, salt and butter until the mixture resembles fine bread crumbs. Pour in water, using more (up to approximately 1/4 cup) if necessary to make a smooth dough. Pat into a ball. Place on a lightly floured surface and knead 10 minutes, or until dough is smooth and elastic. Return to the bowl, cover and set aside.\nHeat oil in a large, deep skillet to 375 degrees F (190 degrees C).\nMelt butter in a medium saucepan over medium high heat. Stir in onion, garlic, green chile peppers and ginger. Cook 5 minutes, or until onions are golden brown. Stir in turmeric, chili powder, ground lamb and salt. Cook until the lamb meat is evenly brown, about 10 minutes. Stir in garam masala and lemon juice. Continue cooking 5 minutes, then remove from heat.\nDivide dough into 15 equal portions. Roll portions into balls, then flatten into 4 inch circles. Cut each circle in half. Dampen edges and form semicircles into cones. Fill cones with equal portions of the lamb meat mixture. Dampen top and bottom edges of cones, and pinch to seal.\nCarefully lower cones into preheated oil a few at a time. Fry until golden brown, 2 to 3 minutes. Drain on paper towels. Serve warm.",
        Name: "Samosas",
        PrepTime: 15.0,
        Review: 4.5,
        ReviewNum: 66.0,
        TotalTime: 50.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "30 samosas",
    },
    {
        CookTime: 56.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5832250.jpg",
        Ingredients: [
            "1 pound lean ground beef",
            "1 medium onion, finely chopped",
            "2 garlic cloves, crushed",
            "2 teaspoons ground coriander",
            "1 \u00bd teaspoons ground cumin",
            "\u00bd teaspoon salt",
            "\u00bd teaspoon ground turmeric",
            "\u00bd teaspoon chile powder, or more to taste",
            "\u00bc teaspoon ground ginger",
            "1 teaspoon garam masala",
            "1 (6 ounce) package frozen peas",
            "\u00bd cup water",
            "1 tablespoon minced pickled jalapeno pepper",
            "1 tablespoon lemon juice",
            "1 (12 ounce) package wonton wrappers",
            "vegetable oil for frying",
        ],
        Instructions:
            "Heat a large skillet over medium heat. Add ground beef, onion, and garlic; cook until beef is browned and crumbly, 5 to 7 minutes. Reduce heat to low.\nMix in coriander, cumin, salt, turmeric, chile powder, and ginger. Add peas and water; bring to boil. Cover and simmer, stirring occasionally, about 25 minutes. Uncover and cook over medium heat, stirring frequently, until any remaining liquid evaporates.\nStir jalapenos and garam masala into the beef mixture. Remove from heat and stir in lemon juice; let cool until safe to handle, at least 15 minutes.\nDrop about 1 tablespoon of the beef mixture onto the center of a wonton wrapper. Moisten edges with water, fold them over the filling, and seal. Repeat with remaining filling and wonton wrappers.\nHeat about 1/2 inch oil in a large saucepan over medium-high heat. Add samosas in batches; fry until browned, 1 to 2 inches per side.",
        Name: "Traditional Beef Samosas",
        PrepTime: 24.0,
        Review: 4.0,
        ReviewNum: 68.0,
        TotalTime: 80.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "24 samosas",
    },
    {
        CookTime: 67.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1011491.jpg",
        Ingredients: [
            "24 chicken wings",
            "2 tablespoons vegetable oil",
            "2 tablespoons soy sauce",
            "2 tablespoons minced green onion",
            "2 cloves garlic, minced",
            "1 teaspoon curry powder",
            "\u00bd teaspoon ground turmeric",
            "\u215b teaspoon ground black pepper",
        ],
        Instructions:
            "Combine chicken wings, vegetable oil, soy sauce, green onion, garlic, curry powder, turmeric, and black pepper in a resealable plastic bag. Squeeze out the air, seal bag, and refrigerate at least 1 hour.\nPreheat oven to 350 degrees F (175 degrees C).\nSpread chicken wings into a large baking dish.\nBake in the preheated oven until wings are browned, about 25 minutes.",
        Name: "Bombay Chicken Wings",
        PrepTime: 28.0,
        Review: 4.5,
        ReviewNum: 63.0,
        TotalTime: 95.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "24 wings",
    },
    {
        CookTime: 35.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5803778.jpg",
        Ingredients: [
            "1 tablespoon vegetable oil",
            "\u00be pound ground beef",
            "1 onion, chopped",
            "1 shallot, minced",
            "1 sprig fresh thyme, chopped",
            "1 tablespoon curry powder",
            "salt and pepper to taste",
            "1 (16 ounce) package phyllo dough",
            "oil for frying",
        ],
        Instructions:
            "Heat oil in a skillet over medium heat and cook beef, onion, shallot, and thyme until meat is brown throughout and crumbly, about 5 minutes. Remove from heat. Season with curry powder, salt, and pepper.\nLay a sheet of phyllo dough on a work surface and cut it lengthways into thirds. Add a spoonful of meat mixture at the top of each strip and fold into triangles, pressing samosa edges together with moistened fingers. Continue with remaining meat mixture.\nHeat oil in a deep fryer or skillet to 400 degrees F (200 degrees C). Deep fry samosas in batches until golden brown, 3 to 5 minutes each.",
        Name: "Easy Beef Samosas",
        PrepTime: 15.0,
        Review: 2.5,
        ReviewNum: 56.0,
        TotalTime: 50.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "10 samosas",
    },
    {
        CookTime: 32.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5271611.jpg",
        Ingredients: [
            "2 tablespoons cornstarch",
            "2 tablespoons rice flour",
            "4 teaspoons cayenne pepper",
            "4 teaspoons paprika",
            "4 teaspoons ground cumin",
            "4 teaspoons garam masala",
            "1 teaspoon ground turmeric",
            "2 teaspoons freshly ground black pepper",
            "4 teaspoons kosher salt",
            "\u00bd cup seasoned rice vinegar",
            "2 tablespoons thinly sliced red onion",
            "1 tablespoon thinly sliced ginger",
            "\u00bd tablespoon minced fresh chives",
            "2 teaspoons sambal chili paste",
            "\u00bd teaspoon red pepper flakes",
            "4 pounds chicken wings",
            "1 teaspoon vegetable oil, or as needed",
            "1 tablespoon freshly grated ginger",
            "2 tablespoons vegetable oil",
        ],
        Instructions:
            "Preheat the oven to 450 degrees F (230 degrees C).\nCombine cornstarch and rice flour in a bowl. Add cayenne pepper, paprika, cumin, garam masala, turmeric, black pepper, and salt. Whisk the spicy chicken coating until nicely blended. Set aside.\nPour rice vinegar into another bowl. Add red onion and sliced ginger. Toss in chives, sambal, and red pepper flakes. Stir the vinegar sauce until well combined.\nAdd wings to the spice coating in batches. Flip bowl repeatedly to toss the wings until thoroughly coated. Transfer wings onto nonstick baking sheets. Drizzle vegetable oil on top.\nBake in the center of the preheated oven for 15 minutes.\nMeanwhile, mix grated ginger and 2 tablespoons oil together. Turn wings over and brush the ginger oil on top.\nContinue baking until dry and browned, 15 to 20 minutes more. An instant-read thermometer inserted near the bone should read 165 degrees F (74 degrees C).\nFlip wings over into the oils and let rest for 3 to 4 minutes. Scrape a fork over the wings to test for crunchiness.\nTo enjoy the wings 'wet,' place a portion of the wings into a bowl and spoon in some of the vinegar sauce. Toss until coated. For 'dry'-style, plate the dry wings and simply dip into the sauce.",
        Name: "Chennai Chicken Wings",
        PrepTime: 13.0,
        Review: 4.0,
        ReviewNum: 92.0,
        TotalTime: 45.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "4 pounds of wings",
    },
    {
        CookTime: 70.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F7616848.jpg",
        Ingredients: [
            "4 tablespoons plain yogurt",
            "1 tablespoon garam masala",
            "1 tablespoon chicken masala powder",
            "1 tablespoon ground coriander",
            "1 tablespoon ginger-garlic paste",
            "1 \u00bd teaspoons chili powder",
            "1 teaspoon ground turmeric",
            "salt to taste",
            "1 \u00bd pounds skinless, boneless chicken breast halves",
            "14 large jalapeno peppers",
            "2 (8 ounce) packages cream cheese (such as Philadelphia\u00ae), softened",
            "2 (8 ounce) packages bacon",
        ],
        Instructions:
            "Combine yogurt, garam masala, chicken masala, coriander, ginger-garlic paste, chili powder, turmeric, and salt in a bowl. Set aside.\nSlice chicken breasts into small strips that will fit on halved jalapenos and place into the bowl with the tikka marinade. Mix well, cover, and let sit in the refrigerator at least 30 minutes; the longer your marinade, the more of a flavor profile on the chicken.\nPreheat the oven to 425 degrees F (220 degrees C). Place a cooling rack on top of a baking tray.\nSnap off jalapeno stems by holding a pepper with one hand and pulling it off to the side. Repeat with remaining peppers. Slice all jalapenos in half lengthwise and remove all seeds and ribbing using a teaspoon, making sure not to remove white stem area.\nFill jalapeno halves with cream cheese using a teaspoon; place as much cheese as to your liking. Place a strip of tikka chicken on top of cream cheese and wrap each chicken popper halve with a slice of bacon. Place on the prepared baking sheet.\nBake in the preheated oven until bacon is browned and crisp, about 40 minutes.",
        Name: "Tikka Chicken Jalapeno Poppers",
        PrepTime: 30.0,
        Review: 3.5,
        ReviewNum: 92.0,
        TotalTime: 100.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "28 jalapeno poppers",
    },
    {
        CookTime: 49.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F292285.jpg",
        Ingredients: [
            "1 tablespoon vegetable oil",
            "1 pound ground chicken",
            "1 onion, diced",
            "1 clove garlic, crushed",
            "salt and ground black pepper to taste",
            "2 tablespoons Madras curry paste (such as Patak's\u00ae)",
            "1 (13.5 ounce) can unsweetened coconut cream",
            "1 bunch fresh cilantro, finely chopped, divided",
            "1 (8 ounce) package phyllo dough",
            "3 \u00bd tablespoons butter, melted",
            "1 egg",
            "2 tablespoons milk",
            "\u00bd cup plain Greek yogurt",
            "\u00bd lemon, juiced",
            "\u00bc teaspoon cayenne pepper",
        ],
        Instructions:
            "Heat oil in a large skillet over medium-high heat. Add chicken, onion, and garlic; cook and stir until chicken is no longer pink, 5 to 10 minutes. Season with salt and pepper. Add curry paste, stirring well. Add coconut cream and mix well. Reduce heat and simmer until thickened, about 15 minutes.\nStir 1/2 of the cilantro into the curry mixture. Remove skillet from heat and let cool completely.\nPreheat the oven to 350 degrees F (175 degrees C).\nBrush each sheet of phyllo dough with melted butter and stack. Cut the phyllo stack into 6 square pieces. Whisk egg and milk in a bowl to make egg wash.\nSpoon some of the curry mixture into the center of 1 square, ensuring you leave a large border. Brush the border with egg wash and fold into a triangle. Pinch the edges securely and place on a baking sheet. Repeat with remaining phyllo and curry mixture. Brush tops of the triangles with egg wash.\nBake in the preheated oven until golden brown, about 30 minutes.\nMake the cilantro yogurt while the triangles bake. Combine remaining cilantro, Greek yogurt, lemon juice, and cayenne pepper in a bowl. Serve with the triangles.",
        Name: "Curried Chicken Phyllo Parcels",
        PrepTime: 21.0,
        Review: 2.0,
        ReviewNum: 80.0,
        TotalTime: 70.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "8 servings",
    },
    {
        CookTime: 56.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4555871.jpg",
        Ingredients: [
            "2 tablespoons Patak's Madras Curry Paste",
            "4 medium potatoes, quartered, cooked",
            "\u2154 cup green peas, cooked",
            "1 cup fresh spinach leaves",
            "1 tablespoon chopped fresh cilantro",
            "2 tablespoons corn flour",
            "vegetable oil for frying",
            "Salt to taste",
        ],
        Instructions:
            "Mash together the cooked potatoes and green peas. Blanch the spinach leaves in boiling water. Drain and plunge into cold water to chill. Squeeze gently to remove excess water. Chop finely.\nAdd the spinach to the potato and pea mixture. Mix well. Add cilantro and Patak's Madras Curry Paste.\nAdd corn flour to bind and mix well, adding salt to taste. Divide the mixture into 24 equal portions. Shape each portion into a ball. Flatten into a thick disk.\nHeat oil in a wok or deep-bottomed frying pan over medium-high heat. When oil is hot but not smoking, fry the patties for 3 to 4 minutes, turning halfway through.\nServe immediately.",
        Name: "Spinach & Green Pea Patties (Hara Bhara Kebabs)",
        PrepTime: 24.0,
        Review: 2.0,
        ReviewNum: 68.0,
        TotalTime: 80.0,
        Type: "appetizer",
        Veg: 0.0,
        Yields: "6 servings",
    },
    {
        CookTime: 56.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F5062814.jpg",
        Ingredients: ["2 cups bread flour", "1 teaspoon salt", "2 tablespoons vegetable oil", "\u2154 cup water"],
        Instructions:
            "In a large bowl, sift together flour and salt. Add oil and mix in with a fork until flour is crumbly. Mix in water until the dough pulls together. Turn dough out onto a lightly floured surface and knead until smooth and elastic, about 8 minutes. Cover and set aside for 45 minutes.\nKnead dough again until smooth; divide into six equal parts. Form each part into a round. Roll out each round as thinly as possible; dust with flour to keep from sticking.\nInvert a heavy cast iron pan over burner and heat. Spread roti over pan and cook. Roti will cook in 40 to 50 seconds. Tiny black spots will appear when it is finished. Fold Roti and serve hot.",
        Name: "Roomali Roti",
        PrepTime: 24.0,
        Review: 2.0,
        ReviewNum: 93.0,
        TotalTime: 80.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "6 rotis",
    },
    {
        CookTime: 46.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F2616940.jpg",
        Ingredients: [
            "1 cup brown rice flour",
            "\u00bd cup whole wheat flour",
            "1 \u00bd cups water",
            "1 red onion, finely chopped",
            "1 clove garlic, minced",
            "\u00bc cup fresh cilantro, chopped",
            "\u00bc teaspoon white sugar",
            "\u00bd teaspoon ground turmeric",
            "1 teaspoon ground cumin",
            "2 teaspoons whole mustard seeds",
            "1 teaspoon cumin seeds",
            "1 teaspoon ground coriander",
            "1 teaspoon ground ginger",
            "1 pinch cayenne pepper",
            "3 tablespoons rice vinegar",
            "1 tablespoon vegetable oil",
        ],
        Instructions:
            "Stir the brown rice and whole wheat flours together in a mixing bowl. Stir in the water to make a thin batter. Add the onion, garlic, cilantro, sugar, turmeric, cumin, mustard seeds, cumin seeds, coriander, ginger, cayenne pepper and rice vinegar until evenly blended. Cover, and refrigerate for at least 1/2 hour, or overnight.\nTo cook the dosas, heat the oil in a skillet over medium heat. Pour 1/4 cup of batter into the skillet, spreading it over the bottom in a thin layer. Cook 1 minute, turn, and cook 1 minute more. Remove from the pan. Repeat with remaining batter.",
        Name: "Dosas (Indian-style Pancakes)",
        PrepTime: 19.0,
        Review: 4.5,
        ReviewNum: 98.0,
        TotalTime: 65.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "8 pancakes",
    },
    {
        CookTime: 14.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F4418816.jpg",
        Ingredients: ["2 \u00bd cups whole wheat flour", "\u00be teaspoon salt", "1 cup water"],
        Instructions:
            "Mix flour and salt together in a bowl. Stir in water to form a soft dough.\nTurn dough out onto a lightly floured work surface and knead several times. Divide into 8 pieces and roll each into a ball. Roll each ball into a very thin round using a rolling pin.\nHeat a griddle over medium-high heat. Cook each dough round on griddle until dough bubbles and blisters appear, about 2 minutes. Flip and cook until lightly browned on the other side.",
        Name: "Quick Whole Wheat Chapati",
        PrepTime: 6.0,
        Review: 2.5,
        ReviewNum: 53.0,
        TotalTime: 20.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "8 servings",
    },
    {
        CookTime: 126.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1016308.jpg",
        Ingredients: [
            "1 (.25 ounce) package active dry yeast",
            "1 cup warm water",
            "\u00bc cup white sugar",
            "3 tablespoons milk",
            "1 egg, beaten",
            "2 teaspoons salt",
            "4 \u00bd cups bread flour",
            "2 teaspoons minced garlic",
            "\u00bc cup butter, melted",
        ],
        Instructions:
            "In a large bowl, dissolve yeast in warm water. Let stand about 10 minutes, until frothy. Stir in sugar, milk, egg, salt, and enough flour to make a soft dough. Knead for 6 to 8 minutes on a lightly floured surface, or until smooth. Place dough in a well oiled bowl, cover with a damp cloth, and set aside to rise. Let it rise 1 hour, until the dough has doubled in volume.\nPunch down dough, and knead in garlic. Pinch off small handfuls of dough about the size of a golf ball. Roll into balls, and place on a tray. Cover with a towel, and allow to rise until doubled in size, about 30 minutes.\nDuring the second rising, preheat grill to high heat.\nAt grill side, roll one ball of dough out into a thin circle. Lightly oil grill. Place dough on grill, and cook for 2 to 3 minutes, or until puffy and lightly browned. Brush uncooked side with butter, and turn over. Brush cooked side with butter, and cook until browned, another 2 to 4 minutes. Remove from grill, and continue the process until all the naan has been prepared.",
        Name: "Naan",
        PrepTime: 54.0,
        Review: 2.0,
        ReviewNum: 99.0,
        TotalTime: 180.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "14 servings",
    },
    {
        CookTime: 21.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F3148477.jpg",
        Ingredients: [
            "1 cup whole wheat flour",
            "1 cup all-purpose flour",
            "1 teaspoon salt",
            "2 tablespoons olive oil",
            "\u00be cup hot water or as needed",
        ],
        Instructions:
            "In a large bowl, stir together the whole wheat flour, all-purpose flour and salt. Use a wooden spoon to stir in the olive oil and enough water to make a soft dough that is elastic but not sticky. Knead the dough on a lightly floured surface until it is smooth. Divide into 10 parts, or less if you want bigger breads. Roll each piece into a ball. Let rest for a few minutes.\nHeat a skillet over medium heat until hot, and grease lightly. On a lightly floured surface, use a floured rolling pin to roll out the balls of dough until very thin like a tortilla. When the pan starts smoking, put a chapati on it. Cook until the underside has brown spots, about 30 seconds, then flip and cook on the other side. Continue with remaining dough.",
        Name: "Indian Chapati Bread",
        PrepTime: 9.0,
        Review: 2.0,
        ReviewNum: 68.0,
        TotalTime: 30.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "10 servings",
    },
    {
        CookTime: 21.0,
        Image:
            "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F8103869.jpg",
        Ingredients: ["1 \u00bc cups self-rising flour, or more as needed", "1 cup whole-milk Greek yogurt"],
        Instructions:
            "Mix self-rising flour and Greek yogurt together in a large bowl until combined. Transfer to a lightly floured work surface and knead until smooth, adding more flour as necessary to keep dough from sticking, 2 to 3 minutes.\nPat dough into a rough 9x7-inch rectangle. Divide into 8 equal pieces. Lightly dust each piece with flour and flatten into a semi-rectangular shape, about 1/4 inch thick.\nLightly grease a large skillet and place it over medium heat. Add 1 or 2 of the flattened dough pieces to the skillet. Cook until they begin to bubble and brown, 2 to 4 minutes. Flip over and cook an additional 2 to 4 minutes. Remove from heat and repeat with remaining dough until all pieces are cooked. Serve warm.",
        Name: "Two-Ingredient Naan",
        PrepTime: 9.0,
        Review: 4.0,
        ReviewNum: 95.0,
        TotalTime: 30.0,
        Type: "bread",
        Veg: 1.0,
        Yields: "8 naan breads",
    },
];

export default recipes;
